<?php

namespace Modules\Didyouknow\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

use Modules\Didyouknow\Entities\Models\Board\Didyouknow;
use Modules\Didyouknow\Entities\Models\Board\Didyouknow_settings;

use Modules\Didyouknow\Entities\Models\Main\Didyouknow_information;

class DidyouknowDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

		$didyouknows = [
			// In draft with user group
			[
				'question' => 'Wist u dat 01',
				'slug' => str_slug('Wist u dat 01', '-'),
				'answer' => 'Dit is dan het antwoord 1',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Users',
			],
			// Author approved with volunteer group
			[
				'question' => 'Wist u dat 2',
				'slug' => str_slug('Wist u dat 2', '-'),
				'answer' => 'Dit is dan het antwoord 2',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Volunteers',
				'author_approve' => 1,
			],
			// Author approved in hands of editor from board
			[
				'question' => 'Wist u dat 3',
				'slug' => str_slug('Wist u dat 3', '-'),
				'answer' => 'Dit is dan het antwoord 3',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
			],
			// editor approved
			[
				'question' => 'Wist u dat 4',
				'slug' => str_slug('Wist u dat 4', '-'),
				'answer' => 'Dit is dan het antwoord 4',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
			],
			// In hands of publisher
			[
				'question' => 'Wist u dat 5',
				'slug' => str_slug('Wist u dat 5', '-'),
				'answer' => 'Dit is dan het antwoord 5',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
				'publisher' => 6,
				'publisher_group' => 'Boardmembers',
			],
			// Fully approved and published now and forever
			[
				'question' => 'Wist u dat 6',
				'slug' => str_slug('Wist u dat 6', '-'),
				'answer' => 'Dit is dan het antwoord 6',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
				'publisher' => 6,
				'publisher_group' => 'Boardmembers',
				'publisher_approve' => 1,
				'publish_date_start' => Carbon::now(),
				'publish_date_end' => Carbon::yesterday(),
			],
			// Fully approved and published in 2 weeks and forever
			[
				'question' => 'Wist u dat 7',
				'slug' => str_slug('Wist u dat 7', '-'),
				'answer' => 'Dit is dan het antwoord 7',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
				'publisher' => 6,
				'publisher_group' => 'Boardmembers',
				'publisher_approve' => 1,
				'publish_date_start' => Carbon::now()->addWeeks(2),
				'publish_date_end' => Carbon::yesterday(),
			],
			// Fully approved and published now and for 14 days
			[
				'question' => 'Wist u dat 8',
				'slug' => str_slug('Wist u dat 8', '-'),
				'answer' => 'Dit is dan het antwoord 8',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
				'publisher' => 6,
				'publisher_group' => 'Boardmembers',
				'publisher_approve' => 1,
				'publish_date_start' => Carbon::now(),
				'publish_date_end' => Carbon::now()->addDays(14),
			],
			// Fully approved and published 3 weeks ago and ended 1 week ago
			[
				'question' => 'Wist u dat 9',
				'slug' => str_slug('Wist u dat 9', '-'),
				'answer' => 'Dit is dan het antwoord 9',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
				'publisher' => 6,
				'publisher_group' => 'Boardmembers',
				'publisher_approve' => 1,
				'publish_date_start' => Carbon::now()->subWeeks(3),
				'publish_date_end' => Carbon::now()->subWeeks(1),
			],
			// Fully approved and published now and for 2 days but archived (deleted)
			[
				'question' => 'Wist u dat 10',
				'slug' => str_slug('Wist u dat 10', '-'),
				'answer' => 'Dit is dan het antwoord 10',
				'draft' => 1,
				'author' => 1,
				'author_group' => 'Boardmembers',
				'author_approve' => 1,
				'editor' => 5,
				'editor_group' => 'Boardmembers',
				'editor_approve' => 1,
				'publisher' => 6,
				'publisher_group' => 'Boardmembers',
				'publisher_approve' => 1,
				'publish_date_start' => Carbon::now()->subDays(3),
				'publish_date_end' => Carbon::now()->addDays(14),
				'deleted_at' => Carbon::now(),
			],

		];
		foreach ($didyouknows as $key => $value) {
			Didyouknow::create($value);
		}



		$didyouknows_information = [
			[
				'title' => 'En dit dan? 1',
				'slug' => str_slug('En dit dan? 1', '-'),
				'body' => 'Er komen na iedere avondvierdaagse weer wist u datjes bij.',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => '',
				'editor_group' => '',
				'editor_approve' => '0',
				'publisher' => '',
				'publisher_group' => '',
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-03 20:05:47',
				'updated_at' => '2018-11-03 20:05:47',
			],

			[
				'title' => 'Wist u dit al? 2',
				'slug' => str_slug('Wist u dit al? 2', '-'),
				'body' => 'Met het organiseren van een evenement als de avondvierdaagse zijn er veel dingen waar mensen niet bij stil staan.
	Op deze pagina willen we jullie bekend maken met leuke, grappige, rare maar misschien ook minder leuke weetjes.
	Mocht je nog bekend zijn met een wist u datje dan horen wij dit graag. Hieronder vindt u een aantal van deze stellingen.',
				'draft' => '1',
				'author' => '1',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => '5',
				'editor_group' => 'Boardmember',
				'editor_approve' => '0',
				'publisher' => '',
				'publisher_group' => '',
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-03 20:05:47',
				'updated_at' => '2018-11-03 20:05:47',
			],

			[
				'title' => 'Wist u dit al? 3',
				'slug' => str_slug('Wist u dit al? 3', '-'),
				'body' => 'Met het organiseren van een evenement als de avondvierdaagse zijn er veel dingen waar mensen niet bij stil staan.
	Op deze pagina willen we jullie bekend maken met leuke, grappige, rare maar misschien ook minder leuke weetjes.
	Mocht je nog bekend zijn met een wist u datje dan horen wij dit graag. Hieronder vindt u een aantal van deze stellingen.',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => '5',
				'editor_group' => 'Boardmember',
				'editor_approve' => '1',
				'publisher' => '',
				'publisher_group' => '',
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-03 20:05:47',
				'updated_at' => '2018-11-03 20:05:47',
			],

			[
				'title' => 'Wist u dit ook al? 4',
				'slug' => str_slug('Wist u dit ook al? 4', '-'),
				'body' => 'Met het organiseren van een evenement als de avondvierdaagse zijn er veel dingen waar mensen niet bij stil staan.
	Op deze pagina willen we jullie bekend maken met leuke, grappige, rare maar misschien ook minder leuke weetjes.
	Mocht je nog bekend zijn met een wist u datje dan horen wij dit graag. Hieronder vindt u een aantal van deze stellingen.',
				'draft' => '1',
				'author' => '4',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => '5',
				'editor_group' => 'Boardmember',
				'editor_approve' => '1',
				'publisher' => '4',
				'publisher_group' => 'Boardmember',
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-03 20:05:47',
				'updated_at' => '2018-11-03 20:05:47',
			],

			[
				'title' => 'Wist u dit ook al? 5',
				'slug' => str_slug('Wist u dit ook al? 5', '-'),
				'body' => 'Met het organiseren van een evenement als de avondvierdaagse zijn er veel dingen waar mensen niet bij stil staan.
	Op deze pagina willen we jullie bekend maken met leuke, grappige, rare maar misschien ook minder leuke weetjes.
	Mocht je nog bekend zijn met een wist u datje dan horen wij dit graag. Hieronder vindt u een aantal van deze stellingen.',
				'draft' => '1',
				'author' => '4',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => '5',
				'editor_group' => 'Boardmember',
				'editor_approve' => '1',
				'publisher' => '4',
				'publisher_group' => 'Boardmember',
				'publisher_approve' => '1',
				'publish_date_start' => '2018-11-03 20:05:47',
				'publish_date_end' => '2018-11-02 00:00:00',
				'deleted_at' => NULL,
				'created_at' => '2018-11-03 20:05:47',
				'updated_at' => '2018-11-03 20:05:47',
			],

			[
				'title' => 'Wist u dit ook al? 6',
				'slug' => str_slug('Wist u dit ook al? 6', '-'),
				'body' => 'Met het organiseren van een evenement als de avondvierdaagse zijn er veel dingen waar mensen niet bij stil staan.
	Op deze pagina willen we jullie bekend maken met leuke, grappige, rare maar misschien ook minder leuke weetjes.
	Mocht je nog bekend zijn met een wist u datje dan horen wij dit graag. Hieronder vindt u een aantal van deze stellingen.',
				'draft' => '1',
				'author' => '4',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => '5',
				'editor_group' => 'Boardmember',
				'editor_approve' => '1',
				'publisher' => '4',
				'publisher_group' => 'Boardmember',
				'publisher_approve' => '1',
				'publish_date_start' => '2018-11-03 20:05:47',
				'publish_date_end' => '2018-11-02 00:00:00',
				'deleted_at' => '2018-11-02 01:00:00',
				'created_at' => '2018-11-03 20:05:47',
				'updated_at' => '2018-11-03 20:05:47',
			],

			[
				'title' => 'test 1',
				'slug' => str_slug('test 1', '-'),
				'body' => '<p>Hier ook een test body.</p> 1',
				'draft' => '1','author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 22:58:02',
				'updated_at' => '2018-11-17 22:58:02',
			],

			[
				'title' => 'test 2',
				'slug' => str_slug('test 2', '-'),
				'body' => '<p>Hier ook een test body.</p> 2',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 22:58:09',
				'updated_at' => '2018-11-17 22:58:09',
			],

			[
				'title' => 'test zoveel 1',
				'slug' => str_slug('test zoveel 1\'', '-'),
				'body' => 'author approval 1',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 23:08:26',
				'updated_at' => '2018-11-17 23:08:26',
			],

			[
				'title' => 'test zoveel 2',
				'slug' => str_slug('test zoveel 2', '-'),
				'body' => 'author approval 2',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 23:08:52',
				'updated_at' => '2018-11-17 23:08:52',
			],

			[
				'title' => 'test 3',
				'slug' => str_slug('test 3', '-'),
				'body' => '<p>test voor author approved</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 23:10:17',
				'updated_at' => '2018-11-17 23:10:17',
			],

			[
				'title' => 'Author test',
				'slug' => str_slug('Author test', '-'),
				'body' => '<p>Dit is weer een author test</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 23:13:17',
				'updated_at' => '2018-11-17 23:13:17',
			],

			[
				'title' => 'Editor test',
				'slug' => str_slug('Editor test', '-'),
				'body' => '<p>Dit is een editor test</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '1',
				'editor' => '6',
				'editor_group' => 'Boardmember',
				'editor_approve' => '1',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-17 23:14:14',
				'updated_at' => '2018-11-17 23:14:14',
			],

			[
				'title' => 'Dit is speciaal voor AJ',
				'slug' => str_slug('Dit is speciaal voor AJ', '-'),
				'body' => '<p>Ik wil graag aan AJ laten zien hoe dit werkt.</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-18 09:23:54',
				'updated_at' => '2018-11-18 09:23:54',
			],

			[
				'title' => 'Dit is een succes test',
				'slug' => str_slug('Dit is een succes test', '-'),
				'body' => '<p>Kijken of hij nu wel wilt.</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 09:46:10',
				'updated_at' => '2018-11-19 09:46:10',
			],

			[
				'title' => 'poe eeh',
				'slug' => str_slug('poe eeh', '-'),
				'body' => '<p>Nog maar een test</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 09:52:23',
				'updated_at' => '2018-11-19 09:52:23',
			],

			[
				'title' => 'test 4',
				'slug' => str_slug('test 4', '-'),
				'body' => '<p>iets</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 09:53:58',
				'updated_at' => '2018-11-19 09:53:58',
			],

			[
				'title' => 'test 5',
				'slug' => str_slug('test 5', '-'),
				'body' => '<p>test</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 09:58:49',
				'updated_at' => '2018-11-19 09:58:49',
			],

			[
				'title' => 'Test reload',
				'slug' => str_slug('Test reload\'', '-'),
				'body' => '<p>Kijken voor reload</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:20:05',
				'updated_at' => '2018-11-19 10:20:05',
			],

			[
				'title' => 'pfff',
				'slug' => str_slug('pfff', '-'),
				'body' => '<p>En nog wat</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:26:16',
				'updated_at' => '2018-11-19 10:26:16',
			],

			[
				'title' => 'aardig lijstje',
				'slug' => str_slug('aardig lijstje', '-'),
				'body' => '<p>tis toch wat</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:27:00',
				'updated_at' => '2018-11-19 10:27:00',
			],

			[
				'title' => 'leste',
				'slug' => str_slug('leste', '-'),
				'body' => '<p>dun leste</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:27:43',
				'updated_at' => '2018-11-19 10:27:43',
			],

			[
				'title' => 'test reset form',
				'slug' => str_slug('test reset form', '-'),
				'body' => '<p>Eens kijken wat er gebeurd</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:34:12',
				'updated_at' => '2018-11-19 10:34:12',
			],

			[
				'title' => 'test 6',
				'slug' => str_slug('test 6', '-'),
				'body' => '<p>Weer een testje</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:36:19',
				'updated_at' => '2018-11-19 10:36:19',
			],

			[
				'title' => 'pff test zoveel',
				'slug' => str_slug('pff test zoveel', '-'),
				'body' => '<p>eens kijken wat nu</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:37:55',
				'updated_at' => '2018-11-19 10:37:55',
			],

			[
				'title' => 'leste keer?',
				'slug' => str_slug(' leste keer?', '-'),
				'body' => '<p>Eens kijken wat nu</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-19 10:39:46',
				'updated_at' => '2018-11-19 10:39:46',
			],

			[
				'title' => 'Test',
				'slug' => str_slug('Test', '-'),
				'body' => '<p>Hier eens wat</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-20 13:29:49',
				'updated_at' => '2018-11-20 13:29:49',
			],

			[
				'title' => 'Test 7',
				'slug' => str_slug('Test 7', '-'),
				'body' => '<p>Nog een test</p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-20 13:34:38',
				'updated_at' => '2018-11-20 13:34:38',
			],

			[
				'title' => 'Dit is een HTML test die niet goed zal gaan.',
				'slug' => str_slug('Dit is een HTML test die niet goed zal gaan.', '-'),
				'body' => '<p>Hier zou nu geen html moeten komen te staan.</p><p>Ik denk dat dit wel gaat gebeuren.</p><p><b>Hier moet iets aan gedaan worden.<i>&nbsp;Namelijk een oplossing vinden.</i></b></p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-21 18:41:46',
				'updated_at' => '2018-11-21 18:41:46',
			],

			[
				'title' => 'Dit ging best goed zo.',
				'slug' => str_slug('Dit ging best goed zo.', '-'),
				'body' => '<p>Auto refresh ging niet helemaal goed.</p><p><sup>Eens</sup>&nbsp;Kijken <b>wat er nu <u><sup>Mee gaat gebeuren</sup></u></b><span style="font-size: 24px;">﻿Ben wel benieuwd.</span></p><ul><li><span style="font-size: 24px;">Hoe gaat dit er bijvoorbeeld uit zien?</span></li><li><span style="font-size: 10px;">﻿Of dit dan dat zal er raar uitzien.</span><span style="font-size: 24px;"><br></span></li></ul>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-21 18:47:10',
				'updated_at' => '2018-11-21 18:47:10',
			],

			[
				'title' => 'Javascript test',
				'slug' => str_slug('Javascript test', '-'),
				'body' => '<p><span class="hljs-tag" style="border: 0px; box-sizing: inherit; margin: 0px; padding: 0px; font-size: 12px; vertical-align: baseline; background: 0px 0px; color: rgb(139, 96, 237); font-family: &quot;Source Code Pro&quot;, &quot;Fira Code&quot;, menlo, monospace; white-space: pre-wrap;">&lt;<span class="hljs-name" style="border: 0px; box-sizing: inherit; margin: 0px; padding: 0px; font-weight: 700; vertical-align: baseline; background: 0px 0px; font-style: inherit;">script</span>&gt;</span><span class="javascript" style="border: 0px; box-sizing: inherit; margin: 0px; padding: 0px; font-size: 12px; vertical-align: baseline; background: 0px 0px; color: rgb(255, 255, 255); font-family: &quot;Source Code Pro&quot;, &quot;Fira Code&quot;, menlo, monospace; white-space: pre-wrap;"> alert(<span class="hljs-string" style="border: 0px; box-sizing: inherit; margin: 0px; padding: 0px; font-weight: inherit; vertical-align: baseline; background: 0px 0px; font-style: inherit; color: rgb(110, 220, 196);">\'Hello - Gotcha !!\'</span>) </span><span class="hljs-tag" style="border: 0px; box-sizing: inherit; margin: 0px; padding: 0px; font-size: 12px; vertical-align: baseline; background: 0px 0px; color: rgb(139, 96, 237); font-family: &quot;Source Code Pro&quot;, &quot;Fira Code&quot;, menlo, monospace; white-space: pre-wrap;">&lt;/<span class="hljs-name" style="border: 0px; box-sizing: inherit; margin: 0px; padding: 0px; font-weight: 700; vertical-align: baseline; background: 0px 0px; font-style: inherit;">script</span>&gt;</span><br></p>',
				'draft' => '1',
				'author' => '6',
				'author_group' => 'Boardmember',
				'author_approve' => '0',
				'editor' => NULL,
				'editor_group' => NULL,
				'editor_approve' => '0',
				'publisher' => NULL,
				'publisher_group' => NULL,
				'publisher_approve' => '0',
				'publish_date_start' => NULL,
				'publish_date_end' => NULL,
				'deleted_at' => NULL,
				'created_at' => '2018-11-21 18:50:48',
				'updated_at' => '2018-11-21 18:50:48'
			]
		];
		foreach ($didyouknows_information as $key => $value) {
			Didyouknow_information::create($value);
		}

		$didyouknowsettings = [
			[
				'slug' => str_slug('Set title', '-'),
				'name' => 'set title',
				'description' => 'Title visible on website yes or no',
				'value_bool' => 1,
				'value_text' => '',
			],

			[
				'slug' => str_slug('Set body', '-'),
				'name' => 'set body',
				'description' => 'Body visible on website yes or no',
				'value_bool' => 1,
				'value_text' => '',
			],
		];
		foreach ($didyouknowsettings as $key => $value) {
			Didyouknow_settings::create($value);
		}
    }
}

