<div class="tab-pane" id="garbage" role="tabpanel">

    
        
        

            <div class="template__table_static template__table_responsive">
                <div class="scrollable scrollbar-macosx">
                    Test garbage








                    
                        
                        
                            
                                
                            
                            
                                
                            
                            
                                
                            
                            
                                
                            
                            
                                
                            
                            
                                
                            
                        
                        
                        
                        

                            
                                
                                    
                                
                                
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                
                                
                                    
                                    
                                    
                                    
                                    
                                        
                                    
                                        
                                    
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                        

                                            
                                                
                                                
                                            
                                                
                                                
                                            
                                                
                                                
                                            

                                            
                                            	
                                            	
                                            	
                                            	
                                            	
                                            	
                                            	
                                            	
                                            

                                        

                                        
                                        
                                        
                                                
                                                
                                                
                                                
                                                
                                        
                                            
                                        
                                        
                                        
                                                
                                                
                                                
                                                
                                                
                                        
                                            
                                        
                                        
                                        
                                                
                                                
                                                
                                                
                                                
                                        
                                            
                                        
                                    
                                
                            

                            
                            

                    
                </div>
            </div>


        
            
                
                
            
        

    
</div>